export const REFRESH_INTERVAL = 'REFRESH_INTERVAL'
export const METRICS_INTERVAL = 'METRICS_INTERVAL'
export const APP_NAME = 'APP_NAME'
export const UNLEASH_MODULE_OPTIONS = 'UNLEASH_MODULE_OPTIONS'
